[package]
name = "atm0s-reverse-proxy-relayer"
version = "0.3.0"
edition = "2021"
description = "Server for atm0s-reverse proxy cluster"
license = "MIT"

[dependencies]
protocol = { workspace = true }
protocol-ed25519 = { workspace = true, optional = true }
metrics-dashboard = { workspace = true, features = ["system"], optional = true }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env", "color"] }
quinn = { workspace = true, features = ["ring", "runtime-tokio", "futures-io"] }
rustls = { workspace = true, features = ["ring", "std"] }
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true, features = ["from", "into", "deref", "display"] }
log = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"] }
tokio-util = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }

[features]
default = ["binary"]
binary = ["protocol-ed25519"]
