[package]
name = "agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["default", "attributes", "unstable"] }
async-trait = "0.1.74"
clap = { version = "4.4.11", features = ["derive", "env"] }
futures = "0.3.4"
log = "0.4.20"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }
yamux = "0.13.1"
serde = { version = "1.0.193", features = ["derive"] }
protocol = { path = "../protocol" }
protocol-ed25519 = { path = "../protocol_ed25519", optional = true }
quinn = { version = "0.10.2", default-features = false, features = ["native-certs", "tls-rustls", "log", "runtime-async-std", "futures-io", "ring"] }
rustls = { version = "0.21.0", default-features = false, features = ["quic", "dangerous_configuration"] }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1

[features]
default = ["protocol-ed25519"]