[package]
name = "atm0s-reverse-proxy-protocol-ed25519"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
ed25519-dalek = { version = "2.1.0", features = ["rand_core", "serde", "pkcs8", "pem"] }
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
protocol = { path = "../protocol", package = "atm0s-reverse-proxy-protocol" }