[package]
name = "atm0s-reverse-proxy-agent"
version = "0.3.0"
edition = "2021"
description = "Agent for reverse proxy cluster"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { workspace = true }
protocol-ed25519 = { workspace = true, optional = true }
tokio = { workspace = true, features = ["full"] }
futures = { version = "0.3" }
async-trait = { workspace = true }
log = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true, optional = true }
tokio-native-tls = { workspace = true, optional = true } 

# for binary build
picolog = { workspace = true, optional = true }
argh = { workspace = true, optional = true }

# for tcp protocol
tokio-yamux = { workspace = true, optional = true }

# for quic protocol
quinn = { workspace = true, features = ["ring", "runtime-tokio", "futures-io"], optional = true }
rustls = { workspace = true, features = ["ring", "std"], optional = true }
base64 = { workspace = true, optional = true }

[features]
default = ["binary", "tcp"]
binary = ["protocol-ed25519", "argh", "picolog"]
tcp = ["tokio-yamux", "tokio-native-tls"]
quic = ["quinn", "rustls", "base64", "thiserror"]
