[package]
name = "cert_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcgen = "0.13.1"
rustls = "0.23.8"
clap = { version = "4.4.11", features = ["derive", "env"] }
