[package]
name = "atm0s-reverse-proxy-relayer-quic"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { workspace = true }
tokio = { workspace = true, features = ["full"] }
clap = { workspace = true, features = ["derive", "env", "color"] }
quinn = { workspace = true, features = ["ring", "runtime-tokio", "futures-io"] }
rustls = { workspace = true, features = ["ring", "std"] }
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true, features = ["from", "into", "deref", "display"] }
log = { workspace = true }